<?php
/**
 *
 * This file is automatically generated from your database
 * This fill will only be written once for each table in your database
 *
 * You may use this class to overwrite default methods in the abstract version of this class
 *
 */

namespace libs\models;
use libs\pdo;

class user extends _user {
	
}